### ISSUE TITLE
Minio与SpringBoot项目集成

### ISSUE THREAD

**Issue by y22879451164** [y22879451164/y22879451164.github.io#12]
>[!NOTE] 1. 添加 MinIO 客户端依赖

在您的 Spring Boot 项目的 pom.xml 文件中添加 MinIO 客户端依赖：
```  xml
<dependency>
          <groupId>io.minio</groupId>
          <artifactId>minio</artifactId>
          <version>8.4.3</version>
</dependency>
```
接下来，在application.properties或application.yml中配置Minio的访问信息，例如：
``` yml
minio:
  endpoint: http://localhost:9000
  access-key: YOUR_ACCESS_KEY
  secret-key: YOUR_SECRET_KEY
  bucket-name: your-bucket-name
```
>[!NOTE]2. 创建 MinIO 配置类

创建一个配置类，用于初始化 MinIO 客户端。创建一个名为 MinioConfig 的类：
``` java
import io.minio.MinioClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MinioConfig {


    @Value("${minio.endpoint}")
    private String endpoint;
    @Value("${minio.accessKey}")
    private String accessKey;
    @Value("${minio.secretKey}")
    private String secretKey;

    @Bean
    public MinioClient minioClient() {

        MinioClient minioClient =
                MinioClient.builder()
                        .endpoint(endpoint)
                        .credentials(accessKey, secretKey)
                        .build();
        return minioClient;
    }
}
```
